import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar/Navbar";
import { ReactNode } from "react";


const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Message-Flow App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {




  return (
    <html lang="en" >
      <head>
        <link
          rel="preload"
          as="font"
          href="/_next/static/media/6a44acd4f1e705fc-s.p.woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`bg-white max-sm:p-0 ${publicSans.className} overflow-x-hidden`}
      >
        <AuthProvider>
        {/* <Navbar /> */}
          <div className="w-full items-center justify-center bg-[#1f2a38]">
            {children}
            <Toaster />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
